language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
before_install:
  # use Anaconda to get compiled versions of scipy and numpy,
  # modified from https://gist.github.com/dan-blanchard/7045057
  - wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION pip numpy scipy Cython
  - source activate testenv
  - pip install --pre oslotest  # needed until final release of oslotest?
  - make cython
  - python setup.py install

script:
  - cd /tmp
  - python -m unittest discover lda
